apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-phm-middleware-pgdata
  labels:
    app: pv-phm-middleware-pgdata
    env: dev
  namespace: phm-namespace
  annotations:
    uid: "jn"
    buildinfo: "仅供postgres db使用"
spec:
  nfs:
    path: /usr/local/soft/nas/phm/pgdata
    server: 114.116.93.22
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce