apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-phm-middleware-pgdata
  namespace: phm-namespace
  annotations:
    uid: "jn"
    buildinfo: "仅供postgres db使用使用"
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
  - ReadWriteOnce