server:
  port: 8080
spring:
  datasource:
    core:
      url: jdbc:mysql://114.116.71.214:30003/crrc-core?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: 123456
      driverClass: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
logging:
  level:
    root: info