server:
  port: ${BOOT_CONTAINER_PORT}
spring:
  datasource:
    core:
      url: jdbc:mysql://${MYSQL_DB_HOST}:${MYSQL_DB_PORT}/crrc-core?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: ${MYSQL_DB_USER}
      password: ${MYSQL_DB_PASSWORD}
      driverClass: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
logging:
  level:
    root: ${LOG_LEVEL}