server:
  port: 8080
spring:
  datasource:
    core:
      url: jdbc:mysql://${MYSQL_DB_HOST}:${MYSQL_DB_PORT}/crrc-core?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: ${MYSQL_DB_USER}
      password: ${MYSQL_DB_PASSWORD}
      driverClass: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource