server:
  port: 443
  ssl:
    enabled: true
    key-store: ${KEY_STORE_PATH}
    key-store-type: ${KEY_STORE_TYPE}
    key-alias: ${KEY_ALIAS}
    key-store-password: ${KEY_STORE_PASSWORD}
    client-auth: ${CLIENT_AUTH_TYPE}
  undertow:
    io-threads: ${IO_THREADS_NUM}
    worker-threads: ${WORKER_THREADS_NUM}
    buffer-size: 1024
  use-forward-headers: true
  http2:
    enabled: true
customer:
  server:
    http:
      enable: ${SERVER_HTTP_ENABLE}
spring:
  datasource:
    core:
      url: jdbc:mysql://${MYSQL_DB_HOST}:${MYSQL_DB_PORT}/crrc-core?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: ${MYSQL_DB_USER}
      password: ${MYSQL_DB_PASSWORD}
      driverClass: com.mysql.cj.jdbc.Driver
      minIdleSize: ${DS_CORE_MIN_IDLE_SIZE}
      maxPoolSize: ${DS_CORE_MAX_POOL_SIZE}
    type: com.zaxxer.hikari.HikariDataSource
logging:
  level:
    root: ${LOG_LEVEL}