server:
  port: 443
  ssl:
    enabled: true
    key-store: classpath:undertow_os_hello.p12
    key-store-type: PKCS12
    key-alias: undertow-os-hello
    key-store-password: 1qaz@WSX
    client-auth: want
  undertow:
    io-threads: 4
    worker-threads: 40
    buffer-size: 1024
  use-forward-headers: true
  http2:
    enabled: true
customer:
  server:
    http:
      enable: true
spring:
  datasource:
    core:
      url: jdbc:mysql://114.116.71.214:30003/crrc-core?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: 123456
      driverClass: com.mysql.cj.jdbc.Driver
      minIdleSize: 5
      maxPoolSize: 10
    type: com.zaxxer.hikari.HikariDataSource
logging:
  level:
    root: info