apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-service-users-db
  namespace: dev-namespace
  annotations:
    uid: "jn"
    buildinfo: "仅供 crrc-service-users beta dev使用"
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce