apiVersion: v1
kind: Service
metadata:
  name: app-crrc-base-hello-https
spec:
  selector:
    app: app-crrc-base-hello-https
  ports:
  - port: 8080
    nodePort: 80007
  - port: 443
    nodePort: 80008
  type: NodePort