apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvmysql-core
  labels:
    app: mysql-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /nfs/pv/database
    server: 192.168.1.211