apiVersion: v1
kind: ReplicationController
metadata:
  name: os-hello-world
spec:
  replicas: 3
  selector:
    app: os-hello-world
  template:
    metadata:
      labels:
        app: os-hello-world
    spec:
      containers:
        - name: os-hello-world
          image: jiangnanjava/os-hello-world
          ports:
            - containerPort: 8080