apiVersion: v1
kind: Service
metadata:
  name: nifi-s-line1
  labels:
    app: nifi-s-line1
  namespace: nifi-namespace
spec:
  ports:
  - port: 30001
    name: ltcp
    targetPort: 30001
  - port: 30002
    name: stcp
    targetPort: 30002
  clusterIP: None
  selector:
    app: nifi