apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpl-phm-middleware-nifi
  labels:
    app: dpl-phm-middleware-nifi
    version: v1
    env: dev
    arc: middleware
  annotations:
    uid: "jn"
    buildinfo: "phm项目开发使用的集成环境-nifi"
    contract: "dpl联系人 姜楠：15542323694"
    realease: "版本为phm开发环境，不可乱动"
  namespace: phm-namespace
spec:
  replicas: 1
  template:
    metadata:
      name: dpl-phm-middleware-nifi
      labels:
        app: dpl-phm-middleware-nifi
    spec:
      containers:
      - name: phm-middleware-nifi
        image: apache/nifi:1.3.0
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: dpl-phm-middleware-nifi
