apiVersion: v1
kind: ConfigMap
metadata:
  name: crrc-service-users-dev
  namespace: dev-namespace
  annotations:
    uid: "jn"
    buildinfo: "仅供 crrc-service-users beta dev使用"
data:
  CLIENT_AUTH_TYPE: "want"
  DPL_MODE: "env"
  DS_CORE_MAX_POOL_SIZE: "5"
  DS_CORE_MIN_IDLE_SIZE: "2"
  IO_THREADS_NUM: "4"
  KEY_ALIAS: "undertow-os-hello"
  KEY_STORE_PASSWORD: "1qaz@WSX"
  KEY_STORE_PATH: "classpath:undertow_os_hello.p12"
  KEY_STORE_TYPE: "PKCS12"
  LOG_LEVEL: "debug"
  MYSQL_DB_HOST: "localhost"
  MYSQL_DB_PASSWORD: "123456"
  MYSQL_DB_PORT: "3306"
  MYSQL_DB_USER: "root"
  SERVER_HTTP_ENABLE: "true"
  WORKER_THREADS_NUM: "40"
