apiVersion: v1
kind: ConfigMap
metadata:
  name: crrc-service-users-dev
  namespace: dev-namespace
  annotations:
    uid: "jn"
    buildinfo: "仅供 crrc-service-users beta dev使用"
data:
  CLIENT_AUTH_TYPE: "want"
  DPL_MODE: "env"
  DS_CORE_MAX_POOL_SIZE: "5"
  DS_CORE_MIN_IDLE_SIZE: "2"
  IO_THREADS_NUM: "4"
  KEY_ALIAS: "undertow-os-hello"
  KEY_STORE_PASSWORD: "1qaz@WSX"
  KEY_STORE_PATH: "classpath:undertow_os_hello.p12"
  KEY_STORE_TYPE: "PKCS12"
  LOG_LEVEL: "debug"
  MYSQL_DB_HOST: "localhost"
  MYSQL_DB_PASSWORD: "123456"
  MYSQL_DB_PORT: "3306"
  MYSQL_DB_USER: "root"
  SERVER_HTTP_ENABLE: "true"
  WORKER_THREADS_NUM: "40"
  my.cnf: |
  [mysqld]
  pid-file        = /var/run/mysqld/mysqld.pid
  socket          = /var/run/mysqld/mysqld.sock
  datadir         = /var/lib/mysql
  secure-file-priv= NULL
  # Disabling symbolic-links is recommended to prevent assorted security risks
  symbolic-links=0
  lower_case_table_names=1
  max_connections         = 3000
  connect_timeout         = 5
  wait_timeout            = 600
  max_allowed_packet      = 32M
  thread_cache_size       = 128
  sort_buffer_size        = 4M
  bulk_insert_buffer_size = 16M
  tmp_table_size          = 32M
  max_heap_table_size     = 32M

  !includedir /etc/mysql/conf.d/

