apiVersion: v1
kind: Service
metadata:
  name: nifi-services
  labels:
    app: nifi-services
  namespace: nifi-namespace
spec:
  selector:
    app: nifi
  ports:
  - port: 8080
    nodePort: 30000
    name: web
  - port: 8888
    nodePort: 30001
    name: nifi-tcp-demo
  type: NodePort