apiVersion: v1
kind: Service
metadata:
  name: sv-phm-middleware-redis-slave
  namespace: phm-namespace
spec:
  selector:
    app: dpl-phm-middleware-redis-slave
  ports:
# redis-slave端口
  - port: 6379
    nodePort: 30307
    name: redis-phm-slave-6379-30307
  type: NodePort